# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
# 'env' variable must be set in the command line 

replicaCount: 2

secretName: transaction-secret # where's the auth information is stored

image:
  repository: eu.gcr.io/polybius-dev/transaction
  tag: latest
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8080

keyvault:
  uriDev: https://polybius-devkeyvault.vault.azure.net
  uriLive: https://polybius-livekeyvault.vault.azure.net

livenessProbe:
  enabled: true
  path: /health
  port: 8080
  initialDelaySeconds: 20
  periodSeconds: 5

readinessProbe:
  enabled: false

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

